# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

project 'Pravisti.xcodeproj'

target 'Pravisti' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end

    # Ensure React modulemap and headers are present in all React.framework slices
    xcframework_path = File.join(installer.sandbox.root, 'React-Core-prebuilt', 'React.xcframework')
    source_modulemap = File.join(xcframework_path, 'Modules', 'module.modulemap')
    source_headers = File.join(xcframework_path, 'Headers')
    if File.exist?(source_modulemap)
      Dir.glob(File.join(xcframework_path, '**/React.framework/Modules')).each do |mod_dir|
        FileUtils.mkdir_p(mod_dir)
        FileUtils.cp(source_modulemap, mod_dir)
      end
    end
    if File.directory?(source_headers)
      Dir.glob(File.join(xcframework_path, '**/React.framework/Headers')).each do |h_dir|
        FileUtils.cp_r(File.join(source_headers, '.'), h_dir)
      end
    end
  end
end
